# Generated by Django 5.2.6 on 2025-09-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumppost',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('resolved', 'Resolved')], default='verified', max_length=20),
        ),
    ]
