# Generated by Django 5.2.6 on 2025-09-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodule',
            name='category',
            field=models.CharField(choices=[('organic', 'Organic Finds'), ('bamboo', 'Bamboo & Wood'), ('plasticfree', 'Plastic-Free Living'), ('naturalcare', 'Natural Care'), ('upcycled', 'Upcycled Style')], default='organic', max_length=50),
        ),
    ]
